# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/beebop/src/fireos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/beebop/src/fireos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/beebop/src/fireos/CMakeFiles /home/beebop/src/fireos/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/beebop/src/fireos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c

# Build rule for target.
c : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c
.PHONY : c

# fast build rule for target.
c/fast:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/build
.PHONY : c/fast

#=============================================================================
# Target rules for targets named fireos.bin

# Build rule for target.
fireos.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fireos.bin
.PHONY : fireos.bin

# fast build rule for target.
fireos.bin/fast:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/build
.PHONY : fireos.bin/fast

#=============================================================================
# Target rules for targets named init.exe

# Build rule for target.
init.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 init.exe
.PHONY : init.exe

# fast build rule for target.
init.exe/fast:
	$(MAKE) -f CMakeFiles/init.exe.dir/build.make CMakeFiles/init.exe.dir/build
.PHONY : init.exe/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f CMakeFiles/version.dir/build.make CMakeFiles/version.dir/build
.PHONY : version/fast

asmintr.o: asmintr.c.o
.PHONY : asmintr.o

# target to build an object file
asmintr.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/asmintr.c.o
.PHONY : asmintr.c.o

asmintr.i: asmintr.c.i
.PHONY : asmintr.i

# target to preprocess a source file
asmintr.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/asmintr.c.i
.PHONY : asmintr.c.i

asmintr.s: asmintr.c.s
.PHONY : asmintr.s

# target to generate assembly for a file
asmintr.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/asmintr.c.s
.PHONY : asmintr.c.s

boot.o: boot.nasm.o
.PHONY : boot.o

# target to build an object file
boot.nasm.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/boot.nasm.o
.PHONY : boot.nasm.o

disk.o: disk.c.o
.PHONY : disk.o

# target to build an object file
disk.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/disk.c.o
.PHONY : disk.c.o

disk.i: disk.c.i
.PHONY : disk.i

# target to preprocess a source file
disk.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/disk.c.i
.PHONY : disk.c.i

disk.s: disk.c.s
.PHONY : disk.s

# target to generate assembly for a file
disk.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/disk.c.s
.PHONY : disk.c.s

elf.o: elf.c.o
.PHONY : elf.o

# target to build an object file
elf.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/elf.c.o
.PHONY : elf.c.o

elf.i: elf.c.i
.PHONY : elf.i

# target to preprocess a source file
elf.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/elf.c.i
.PHONY : elf.c.i

elf.s: elf.c.s
.PHONY : elf.s

# target to generate assembly for a file
elf.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/elf.c.s
.PHONY : elf.c.s

fat.o: fat.c.o
.PHONY : fat.o

# target to build an object file
fat.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/fat.c.o
.PHONY : fat.c.o

fat.i: fat.c.i
.PHONY : fat.i

# target to preprocess a source file
fat.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/fat.c.i
.PHONY : fat.c.i

fat.s: fat.c.s
.PHONY : fat.s

# target to generate assembly for a file
fat.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/fat.c.s
.PHONY : fat.c.s

gdt_c.o: gdt_c.c.o
.PHONY : gdt_c.o

# target to build an object file
gdt_c.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/gdt_c.c.o
.PHONY : gdt_c.c.o

gdt_c.i: gdt_c.c.i
.PHONY : gdt_c.i

# target to preprocess a source file
gdt_c.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/gdt_c.c.i
.PHONY : gdt_c.c.i

gdt_c.s: gdt_c.c.s
.PHONY : gdt_c.s

# target to generate assembly for a file
gdt_c.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/gdt_c.c.s
.PHONY : gdt_c.c.s

gdt_s.o: gdt_s.nasm.o
.PHONY : gdt_s.o

# target to build an object file
gdt_s.nasm.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/gdt_s.nasm.o
.PHONY : gdt_s.nasm.o

idt_c.o: idt_c.c.o
.PHONY : idt_c.o

# target to build an object file
idt_c.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/idt_c.c.o
.PHONY : idt_c.c.o

idt_c.i: idt_c.c.i
.PHONY : idt_c.i

# target to preprocess a source file
idt_c.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/idt_c.c.i
.PHONY : idt_c.c.i

idt_c.s: idt_c.c.s
.PHONY : idt_c.s

# target to generate assembly for a file
idt_c.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/idt_c.c.s
.PHONY : idt_c.c.s

idt_s.o: idt_s.nasm.o
.PHONY : idt_s.o

# target to build an object file
idt_s.nasm.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/idt_s.nasm.o
.PHONY : idt_s.nasm.o

inthandle.o: inthandle.c.o
.PHONY : inthandle.o

# target to build an object file
inthandle.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/inthandle.c.o
.PHONY : inthandle.c.o

inthandle.i: inthandle.c.i
.PHONY : inthandle.i

# target to preprocess a source file
inthandle.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/inthandle.c.i
.PHONY : inthandle.c.i

inthandle.s: inthandle.c.s
.PHONY : inthandle.s

# target to generate assembly for a file
inthandle.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/inthandle.c.s
.PHONY : inthandle.c.s

irq.o: irq.c.o
.PHONY : irq.o

# target to build an object file
irq.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/irq.c.o
.PHONY : irq.c.o

irq.i: irq.c.i
.PHONY : irq.i

# target to preprocess a source file
irq.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/irq.c.i
.PHONY : irq.c.i

irq.s: irq.c.s
.PHONY : irq.s

# target to generate assembly for a file
irq.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/irq.c.s
.PHONY : irq.c.s

kernel.o: kernel.c.o
.PHONY : kernel.o

# target to build an object file
kernel.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/kernel.c.o
.PHONY : kernel.c.o

kernel.i: kernel.c.i
.PHONY : kernel.i

# target to preprocess a source file
kernel.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/kernel.c.i
.PHONY : kernel.c.i

kernel.s: kernel.c.s
.PHONY : kernel.s

# target to generate assembly for a file
kernel.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/kernel.c.s
.PHONY : kernel.c.s

keyboard.o: keyboard.c.o
.PHONY : keyboard.o

# target to build an object file
keyboard.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/keyboard.c.o
.PHONY : keyboard.c.o

keyboard.i: keyboard.c.i
.PHONY : keyboard.i

# target to preprocess a source file
keyboard.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/keyboard.c.i
.PHONY : keyboard.c.i

keyboard.s: keyboard.c.s
.PHONY : keyboard.s

# target to generate assembly for a file
keyboard.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/keyboard.c.s
.PHONY : keyboard.c.s

libc/src/crt0.o: libc/src/crt0.nasm.o
.PHONY : libc/src/crt0.o

# target to build an object file
libc/src/crt0.nasm.o:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/crt0.nasm.o
.PHONY : libc/src/crt0.nasm.o

libc/src/stdio.o: libc/src/stdio.c.o
.PHONY : libc/src/stdio.o

# target to build an object file
libc/src/stdio.c.o:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/stdio.c.o
.PHONY : libc/src/stdio.c.o

libc/src/stdio.i: libc/src/stdio.c.i
.PHONY : libc/src/stdio.i

# target to preprocess a source file
libc/src/stdio.c.i:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/stdio.c.i
.PHONY : libc/src/stdio.c.i

libc/src/stdio.s: libc/src/stdio.c.s
.PHONY : libc/src/stdio.s

# target to generate assembly for a file
libc/src/stdio.c.s:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/stdio.c.s
.PHONY : libc/src/stdio.c.s

libc/src/stdlib.o: libc/src/stdlib.c.o
.PHONY : libc/src/stdlib.o

# target to build an object file
libc/src/stdlib.c.o:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/stdlib.c.o
.PHONY : libc/src/stdlib.c.o

libc/src/stdlib.i: libc/src/stdlib.c.i
.PHONY : libc/src/stdlib.i

# target to preprocess a source file
libc/src/stdlib.c.i:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/stdlib.c.i
.PHONY : libc/src/stdlib.c.i

libc/src/stdlib.s: libc/src/stdlib.c.s
.PHONY : libc/src/stdlib.s

# target to generate assembly for a file
libc/src/stdlib.c.s:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/stdlib.c.s
.PHONY : libc/src/stdlib.c.s

libc/src/string.o: libc/src/string.c.o
.PHONY : libc/src/string.o

# target to build an object file
libc/src/string.c.o:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/string.c.o
.PHONY : libc/src/string.c.o

libc/src/string.i: libc/src/string.c.i
.PHONY : libc/src/string.i

# target to preprocess a source file
libc/src/string.c.i:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/string.c.i
.PHONY : libc/src/string.c.i

libc/src/string.s: libc/src/string.c.s
.PHONY : libc/src/string.s

# target to generate assembly for a file
libc/src/string.c.s:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/string.c.s
.PHONY : libc/src/string.c.s

libc/src/syscall.o: libc/src/syscall.nasm.o
.PHONY : libc/src/syscall.o

# target to build an object file
libc/src/syscall.nasm.o:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/syscall.nasm.o
.PHONY : libc/src/syscall.nasm.o

libc/src/unistd.o: libc/src/unistd.c.o
.PHONY : libc/src/unistd.o

# target to build an object file
libc/src/unistd.c.o:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/unistd.c.o
.PHONY : libc/src/unistd.c.o

libc/src/unistd.i: libc/src/unistd.c.i
.PHONY : libc/src/unistd.i

# target to preprocess a source file
libc/src/unistd.c.i:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/unistd.c.i
.PHONY : libc/src/unistd.c.i

libc/src/unistd.s: libc/src/unistd.c.s
.PHONY : libc/src/unistd.s

# target to generate assembly for a file
libc/src/unistd.c.s:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/libc/src/unistd.c.s
.PHONY : libc/src/unistd.c.s

malloc.o: malloc.c.o
.PHONY : malloc.o

# target to build an object file
malloc.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/malloc.c.o
.PHONY : malloc.c.o

malloc.i: malloc.c.i
.PHONY : malloc.i

# target to preprocess a source file
malloc.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/malloc.c.i
.PHONY : malloc.c.i

malloc.s: malloc.c.s
.PHONY : malloc.s

# target to generate assembly for a file
malloc.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/malloc.c.s
.PHONY : malloc.c.s

modules/init.o: modules/init.c.o
.PHONY : modules/init.o

# target to build an object file
modules/init.c.o:
	$(MAKE) -f CMakeFiles/init.exe.dir/build.make CMakeFiles/init.exe.dir/modules/init.c.o
.PHONY : modules/init.c.o

modules/init.i: modules/init.c.i
.PHONY : modules/init.i

# target to preprocess a source file
modules/init.c.i:
	$(MAKE) -f CMakeFiles/init.exe.dir/build.make CMakeFiles/init.exe.dir/modules/init.c.i
.PHONY : modules/init.c.i

modules/init.s: modules/init.c.s
.PHONY : modules/init.s

# target to generate assembly for a file
modules/init.c.s:
	$(MAKE) -f CMakeFiles/init.exe.dir/build.make CMakeFiles/init.exe.dir/modules/init.c.s
.PHONY : modules/init.c.s

paging_c.o: paging_c.c.o
.PHONY : paging_c.o

# target to build an object file
paging_c.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/paging_c.c.o
.PHONY : paging_c.c.o

paging_c.i: paging_c.c.i
.PHONY : paging_c.i

# target to preprocess a source file
paging_c.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/paging_c.c.i
.PHONY : paging_c.c.i

paging_c.s: paging_c.c.s
.PHONY : paging_c.s

# target to generate assembly for a file
paging_c.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/paging_c.c.s
.PHONY : paging_c.c.s

paging_s.o: paging_s.nasm.o
.PHONY : paging_s.o

# target to build an object file
paging_s.nasm.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/paging_s.nasm.o
.PHONY : paging_s.nasm.o

printf.o: printf.c.o
.PHONY : printf.o

# target to build an object file
printf.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/printf.c.o
.PHONY : printf.c.o

printf.i: printf.c.i
.PHONY : printf.i

# target to preprocess a source file
printf.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/printf.c.i
.PHONY : printf.c.i

printf.s: printf.c.s
.PHONY : printf.s

# target to generate assembly for a file
printf.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/printf.c.s
.PHONY : printf.c.s

process.o: process.c.o
.PHONY : process.o

# target to build an object file
process.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/process.c.o
.PHONY : process.c.o

process.i: process.c.i
.PHONY : process.i

# target to preprocess a source file
process.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/process.c.i
.PHONY : process.c.i

process.s: process.c.s
.PHONY : process.s

# target to generate assembly for a file
process.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/process.c.s
.PHONY : process.c.s

shell.o: shell.c.o
.PHONY : shell.o

# target to build an object file
shell.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/shell.c.o
.PHONY : shell.c.o

shell.i: shell.c.i
.PHONY : shell.i

# target to preprocess a source file
shell.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/shell.c.i
.PHONY : shell.c.i

shell.s: shell.c.s
.PHONY : shell.s

# target to generate assembly for a file
shell.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/shell.c.s
.PHONY : shell.c.s

stdlib.o: stdlib.c.o
.PHONY : stdlib.o

# target to build an object file
stdlib.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/stdlib.c.o
.PHONY : stdlib.c.o

stdlib.i: stdlib.c.i
.PHONY : stdlib.i

# target to preprocess a source file
stdlib.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/stdlib.c.i
.PHONY : stdlib.c.i

stdlib.s: stdlib.c.s
.PHONY : stdlib.s

# target to generate assembly for a file
stdlib.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/stdlib.c.s
.PHONY : stdlib.c.s

syscall.o: syscall.c.o
.PHONY : syscall.o

# target to build an object file
syscall.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/syscall.c.o
.PHONY : syscall.c.o

syscall.i: syscall.c.i
.PHONY : syscall.i

# target to preprocess a source file
syscall.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/syscall.c.i
.PHONY : syscall.c.i

syscall.s: syscall.c.s
.PHONY : syscall.s

# target to generate assembly for a file
syscall.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/syscall.c.s
.PHONY : syscall.c.s

syscall_handlers.o: syscall_handlers.c.o
.PHONY : syscall_handlers.o

# target to build an object file
syscall_handlers.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/syscall_handlers.c.o
.PHONY : syscall_handlers.c.o

syscall_handlers.i: syscall_handlers.c.i
.PHONY : syscall_handlers.i

# target to preprocess a source file
syscall_handlers.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/syscall_handlers.c.i
.PHONY : syscall_handlers.c.i

syscall_handlers.s: syscall_handlers.c.s
.PHONY : syscall_handlers.s

# target to generate assembly for a file
syscall_handlers.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/syscall_handlers.c.s
.PHONY : syscall_handlers.c.s

timer.o: timer.c.o
.PHONY : timer.o

# target to build an object file
timer.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/timer.c.o
.PHONY : timer.c.o

timer.i: timer.c.i
.PHONY : timer.i

# target to preprocess a source file
timer.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/timer.c.i
.PHONY : timer.c.i

timer.s: timer.c.s
.PHONY : timer.s

# target to generate assembly for a file
timer.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/timer.c.s
.PHONY : timer.c.s

vga.o: vga.c.o
.PHONY : vga.o

# target to build an object file
vga.c.o:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/vga.c.o
.PHONY : vga.c.o

vga.i: vga.c.i
.PHONY : vga.i

# target to preprocess a source file
vga.c.i:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/vga.c.i
.PHONY : vga.c.i

vga.s: vga.c.s
.PHONY : vga.s

# target to generate assembly for a file
vga.c.s:
	$(MAKE) -f CMakeFiles/fireos.bin.dir/build.make CMakeFiles/fireos.bin.dir/vga.c.s
.PHONY : vga.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... c"
	@echo "... edit_cache"
	@echo "... fireos.bin"
	@echo "... init.exe"
	@echo "... rebuild_cache"
	@echo "... version"
	@echo "... asmintr.o"
	@echo "... asmintr.i"
	@echo "... asmintr.s"
	@echo "... boot.o"
	@echo "... disk.o"
	@echo "... disk.i"
	@echo "... disk.s"
	@echo "... elf.o"
	@echo "... elf.i"
	@echo "... elf.s"
	@echo "... fat.o"
	@echo "... fat.i"
	@echo "... fat.s"
	@echo "... gdt_c.o"
	@echo "... gdt_c.i"
	@echo "... gdt_c.s"
	@echo "... gdt_s.o"
	@echo "... idt_c.o"
	@echo "... idt_c.i"
	@echo "... idt_c.s"
	@echo "... idt_s.o"
	@echo "... inthandle.o"
	@echo "... inthandle.i"
	@echo "... inthandle.s"
	@echo "... irq.o"
	@echo "... irq.i"
	@echo "... irq.s"
	@echo "... kernel.o"
	@echo "... kernel.i"
	@echo "... kernel.s"
	@echo "... keyboard.o"
	@echo "... keyboard.i"
	@echo "... keyboard.s"
	@echo "... libc/src/crt0.o"
	@echo "... libc/src/stdio.o"
	@echo "... libc/src/stdio.i"
	@echo "... libc/src/stdio.s"
	@echo "... libc/src/stdlib.o"
	@echo "... libc/src/stdlib.i"
	@echo "... libc/src/stdlib.s"
	@echo "... libc/src/string.o"
	@echo "... libc/src/string.i"
	@echo "... libc/src/string.s"
	@echo "... libc/src/syscall.o"
	@echo "... libc/src/unistd.o"
	@echo "... libc/src/unistd.i"
	@echo "... libc/src/unistd.s"
	@echo "... malloc.o"
	@echo "... malloc.i"
	@echo "... malloc.s"
	@echo "... modules/init.o"
	@echo "... modules/init.i"
	@echo "... modules/init.s"
	@echo "... paging_c.o"
	@echo "... paging_c.i"
	@echo "... paging_c.s"
	@echo "... paging_s.o"
	@echo "... printf.o"
	@echo "... printf.i"
	@echo "... printf.s"
	@echo "... process.o"
	@echo "... process.i"
	@echo "... process.s"
	@echo "... shell.o"
	@echo "... shell.i"
	@echo "... shell.s"
	@echo "... stdlib.o"
	@echo "... stdlib.i"
	@echo "... stdlib.s"
	@echo "... syscall.o"
	@echo "... syscall.i"
	@echo "... syscall.s"
	@echo "... syscall_handlers.o"
	@echo "... syscall_handlers.i"
	@echo "... syscall_handlers.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... vga.o"
	@echo "... vga.i"
	@echo "... vga.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

